// <auto-generated />
namespace Silownia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dodanieIDkówdoklasyUmowa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodanieIDkówdoklasyUmowa));
        
        string IMigrationMetadata.Id
        {
            get { return "201510122012250_dodanie ID-ków do klasy Umowa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
