// <auto-generated />
namespace Silownia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dodaniewiadomosci : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodaniewiadomosci));
        
        string IMigrationMetadata.Id
        {
            get { return "201512061514030_dodanie wiadomosci"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
