<?xml version="1.0" encoding="utf-8"?><Database Name="inzSilownie" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=db-mssql.pjwstk.edu.pl;Initial Catalog=inzSilownie;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SilowniaContext" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TreningPersonalny" Member="TreningPersonalnies">
    <Type Name="TreningPersonalny">
      <Column Name="TreningID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Klient_OsobaID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Trener_OsobaID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZajeciaGrup" Member="ZajeciaGrups">
    <Type Name="ZajeciaGrup">
      <Column Name="TreningID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Sala_Numer_sali" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Trener_OsobaID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Instruktor_OsobaID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NazwaTreningu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OpisTreningu" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TreningWlasny" Member="TreningWlasnies">
    <Type Name="TreningWlasny">
      <Column Name="TreningID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Klient_OsobaID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>